import MyApp from './_app';
import './globals.css';
import Header from './header';
import type { Metadata } from 'next';
import { Toolbar } from '@mui/material';
import UserDisplayNudge from './index/ud-nudge';
import { Geist, Geist_Mono } from 'next/font/google';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Ukan Wears',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MyApp>
          <Header />
          <Toolbar />
          <UserDisplayNudge />
          {children}
        </MyApp>
      </body>
    </html>
  );
}
